### ISSUE TITLE
tests for user dashboard

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend-functional-tests#15]
We want to test `dashboard` page for number of datasets, so we can see it works properly

## Acceptance criteria

* [ ] Dashboard page is tested

## Tasks

* [ ] analysis
* [ ] prepare new dataset
* [ ] wirte tests
* [ ] test on your own account
* [ ] update `travis.yml`

## Analysis

Prepare dataset to publish. 
Whenever we publish dataset, it should be considered as a new dataset, so we can see changes on `dashboard` page.

Steps:
* Load dashboard page to see current total datasets and size
* After publishing run tests to compare new number(incremented by one) with old number(incremented by one) and size should increase

Write small function to update dataset `name` prior to pushing it, so it will publish new dataset with travis ci
