### ISSUE TITLE
Fix the broken functional tests

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend-functional-tests#17]
As the Datahub team, we want to put back frontend functional tests so that we can monitor status of our website.

## Acceptance criteria

* [x] funcional tests are running on daily basis without errors on Travis

## Tasks

* [x] analyse and identify the source of broken tests
* [x] fix them
* [x] start running on Travis again

**Comment by anuveyatsu** [comment]
FIXED
