### ISSUE TITLE
setup travis to run check daily 

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend-functional-tests#3]
We want to setup travis.yml so we can run our tests daily

## Acceptance criteria 

* [x] tests run on travis daily

## Tasks

* [x] setup travis cron jobs to daily
* [x] refactor code by adding assertion for each test

## Analysis

push.sh
```

#!/bin/sh

setup_git() {
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"
}

commit_website_files() {
  git checkout -b master
  git add status.csv
  git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
}

upload_files() {
  git push origin master
}

setup_git
commit_website_files
upload_files
```

`.travis.yml`
```
language: node_js

node_js:
  - "8"

install:
  - npm install

script: npm run check

deploy:
  script: push.sh
  on:
    branch: master
```

**Comment by zelima** [comment]
@Mikanebu I guess this is now fixed, right?

**Comment by Mikanebu** [comment]
@zelima yes, but I will update acceptance criteria, it changed

**Comment by Mikanebu** [comment]
FIXED, now tests run on travis daily, we can check travis build status, if it fails, we can take a look on travis logs, otherwise all tests are passed
