### ISSUE TITLE
test private dataset on testing and production environment

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend-functional-tests#5]
We want to test frontend for private datasets, so everything loads fine.

## Acceptance criteria

* [x] private dataset is tested on testing and production environment

## Tasks

* [x] refactor `main.js` to use cookies
* [x] publish sample private dataset to test

**Comment by Mikanebu** [comment]
FIXED, now we test frontend for private datasets
