### ISSUE TITLE
Refactor all the tests due to update on backend

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend-functional-tests#7]
We want to refactor our tests, so it passes with new updated backend

## Acceptance criteria

* [x] All tests are passed successfully 

## Tasks

* [x] Refactor `api.test.js`
* [x] Refactor `statuses.test.js`

**Comment by Mikanebu** [comment]
FIXED, all tests updated with new backend changes
