### ISSUE TITLE
Frontend testing for data validation

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend-functional-tests#8]
We want to test frontend by adding various data validation scenarios, so we can get report if something goes wrong

## Acceptance criteria

* [x] data validation with different scenarios are tested

## Tasks

* [x] Prepare detailed analysis and set of tasks that covers validation scenarios(2h)
* [ ] adding various data validation scenarios(5h)
  * [x] Big / Small invalid dataset (cause CSV to fail before / after validation) ?
    * [x] Create big public invalid dataset(size ~1-2mb)
    * [x] Create small private invalid dataset(size ~1-5kb)
    * [x] Publish using `travis.yml`
    * [x] Test using specstore API for status
    * [x] Test validation output on frontend
  * [x] Datasets that fail validation but not pipeline (Eg: duplicate row) (covered)
    * [x] Create sample invalid dataset with duplication row
    * [x] Publish with `travis.yml`
    * [x] Test using specstore API for status
    * [x] Test validation report(Goodtables report if necessary)
  * [x] Different validation errors, make sure we see them as well( missing required properties in `datapackage.json`) (covered)
    * [x] It will be part of big invalid dataset testing
  * [x] Multiple resources with issues(covered)
    * [x] It will be part of small invalid dataset test
  * [x] Multiple errors per file
    * [x] It will be part of processing input small invalid dataset test
  * [x] Private / Public (covered)
    * [x] it will be part of big and small dataset testing
  * [ ] Excel as source (covered)
    * [ ] it will be part of small invalid dataset test
  * [x] Processing input
    * [x] create sample invalid dataset with `flow.yml` configuration
    * [x] publish using `travis.yml`
    * [x] add tests for specstore status
    * [x] add tests for entire page
  * [x] Check redirect (covered)
    * [x] Create sample valid dataset
    * [x] Add into `travis.yml` to publish prior testing
    * [x] Test using specstore API for `revisionId` and `latest`, it should have a `state: successful` for both cases
    * [x] Test entire main page(not revision) for all properties such as views, tables, headers etc.

## Analysis

We have to push datasets prior to testing. So we can setup `travis.yml` as follows:
```
language: node_js
node_js:
- '8'

install:
- npm install
- npm install -g git+https://github.com/datahq/datahub-cli.git

before_script:
- data push fixtures/big-invalid-dataset
- sleep 20000
env:
  global:
    id: examples
    username: examples
  TRAVIS_SECURE_ENV_VARS: true

script: npm run test
```
Since we push it reqularty, we need to get exact url 
Test the following part in frontend:
* `Processing this revision has failed. See below for details:` message
* `Creating CSV`
* `tableschema.exceptions.CastError: There are 1 cast errors (see exception.errors)`
* `Some of your data has validation errors. Please, scroll down to see validation report.`
* `Goodtables report for number of rows`

When I push dataset by `travis.yml`:
How can I get `url`  for my tests, since revisionId will be changed whenever I push dataset?

I can add function to push dataset directly from my tests  by calling `datahub.push`
```
const res = await datahub.push(dataset, options)
```
so I can get `revisionId` in the response body, and setup timeout to wait until it publishes and pass to my test function. Then, I can test whatever I want... using `puppeteer` and `cheerio` libraries. 

### Cases: 

* Valid dataset - test redirection
* Invalid dataset with `flow.yml`
* Invalid dataset with multiple resources - to test multiple resources with issues and `excel` as source, plus public dataset, small(~5kb)
  * resource `excel`
  * resource `csv` - invalid(missing required properties like `title`)
  * findability `public`
* Invalid dataset - to test datasets that fail validation but not pipeline, plus for `private` and size `big`(~1mb)
  * findability `private`
* Invalid dataset with duplicated row

In total 5 invalid datasets cover entire scenario.

### Updates

We decided not to use `datahub.push` method, instead we can use `travis CI` and get revision id by requesting specstore, since we have API for it. 

Then testing specstore, plus entire frontend for all properties same as for testing `finance-vix` dataset.

**Comment by zelima** [comment]
@Mikanebu What about testing spec store API itself - with the correct flow and pipeline statuses etc?... also:
>How can I get url for my tests, since revisionId will be changed whenever I push dataset?

You can get it by hitting specstore API `source/owner/dataset_name/latest`, but you can do in your way as well, if you think it's better

Also what about the one that needs processing?

**Comment by Mikanebu** [comment]
@zelima Great! Missed this part, I will check spec store API as well. Could you give me more info about `processing input` and `Big / Small invalid dataset (cause CSV to fail before / after validation) `? Could you give me more example for this?

**Comment by zelima** [comment]
Well 
* big dataset would be dataset with csv file ~1 mb 
* small less then ~5kb 
* needs processing - one that eg needs to remove first 5 rows from CSV file

**Comment by Mikanebu** [comment]
FIXED, this issue mainly fixed, and it will continue as a specific cases in https://github.com/datahq/frontend-functional-tests/issues/12

**Comment by Mikanebu** [comment]
FIXED, this issue mainly fixed, and it will continue as a specific cases in #12
